version: "2"
services:
  api:
    image: node:6-alpine
    command: npm start
    volumes:
      - ./oscar-api:/app
    ports:
      - "3001:8080"
    working_dir: /app
    environment:
      NODE_CONFIG: '{"db":{"host":"db","port":27017,"db":"oscars"},"auth":{"secret":"secret","admins":["admin"]},"score":{"correct":10,"incorrect":0},"log":{"level":"INFO"}}'
    links:
      - db
  db:
    image: mongo:3
    ports:
      - "27018:27017"
